language: python

matrix:
  include:
    - os: windows
      language: sh
      python: 3.8  # only works on linux
      before_install:
        - choco install python3 --version 3.8 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
    - os: windows
      language: sh
      python: 3.7  # only works on linux
      before_install:
        - choco install python3 --version 3.7 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
    - os: windows
      language: sh
      python: 3.6  # only works on linux
      before_install:
        - choco install python3 --version 3.6.1 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
    - os: linux
      python: 3.7  # only works on
    - os: linux
      python: 3.6  # only works on linux
    - os: linux
      python: 3.8  # only works on linux

branches:
  only:
    - master
    - develop

install:
  - pip install --upgrade pytest
  - pip install ".[dev]" . # install package + dev dependencies


script:
  - pytest

after_success:
  - codecov # submit coverage