language: python
python:
  - 3.6
  - 3.7
os:
  - windows
  - linux

branches:
  only:
    - master
    - develop

install:
  - pip install ".[dev]" . # install package + dev dependencies
  - pip install --upgrade pytest

script:
  - pytest

after_success:
  - codecov # submit coverage