language: python
python:
  - 3.6
  - 3.7

branches:
  only:
    - master
    - develop

install:
  - pip install ".[dev]" . # install package + test dependencies

script:
  - pytest

after_success:
  - codecov # submit coverage