language: python

matrix:
  include:
    - os: windows
      language: sh
      python: 3.7  # only works on linux
      before_install:
        - choco install python3 --version 3.7 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: 3.6  # only works on linux
      before_install:
        - choco install python3 --version 3.6 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: linux
      python: 3.7  # only works on
    - os: linux
      python: 3.6  # only works on linux

branches:
  only:
    - master
    - develop

install:
  - pip install ".[dev]" . # install package + dev dependencies
  - pip install --upgrade pytest

script:
  - pytest

after_success:
  - codecov # submit coverage